### PR TITLE
Added github workflow for multi arch docker images

### PR DESCRIPTION
**Pull request by Der-Henning**
Workflow creates docker images for the following os/arch:

- linux/arm/v6
- linux/arm/v7
- linux/amd64
- linux/arm64/v8

Workflow requires set repository secrets for docker hub credentials:

- DOCKER_USERNAME
- DOCKER_PASSWORD

The workflow creates and pushes an image with tag "latest" on every push to the main branch. Pushing a tag creates an image with the same tag.

### CODE REVIEW

**Comment by Der-Henning** [comment]
I could only test the created images on amd64 so far. Will test on arm64, arm/v6 and arm/v7 tomorrow.

**Comment by GioF71** [comment]
Hello, thank you for your contribution.
I am currently working on this branch (https://github.com/GioF71/squeezelite-docker/tree/feature/issue-12-build-all-versions-with-the-same-dockerfile) in order to eliminate all those release branches, then I will come back and integrate your work.
Do you think it will be possible to trigger the build ofd all my usual versions (buster, bullseye, sourceforge-bullseye, stable, latest etc along with those with the dates)?
Again, thank you, much appreciated!

**Comment by Der-Henning** [comment]
Hi. Yes. We have to create a Dockerfile for every source (for every different "recipe"). The base image can be set with an argument.

```
ARG VARIANT=buster-20211220-slim
FROM debian:${VARIANT}
```

In the workflow we create a matrix to run a job for every variant and source combination:

```
jobs:
    release:
        name: Release Image
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                variant: [ 'buster-20211220-slim', 'bullseye-20211220-slim' ]
                source: ['apt', 'sourceforge']

[...]

        -
            name: Set Release Tag
            run: |
                SOURCE="" \
                if [ "${{ matrix.source}}" = "sourceforge" ]; \
                then SOURCE="sourceforge-"; fi \
                if [ "${GITHUB_REF#refs/*/}" = "main" ]; \
                then echo "RELEASE_TAG=${SOURCE}latest"; \
                else echo "RELEASE_TAG=${SOURCE}${{ matrix.variant}}-${GITHUB_REF#refs/*/}"; fi \
                >> $GITHUB_ENV

[...]

        -
            name: Build and push image
            uses: docker/build-push-action@v2
            with:
                context: .
                file: Dockerfile.${{ matrix.source}}
                build-args: VARIANT=${{ matrix.variant}}
                platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/squeezelite:${{ env.RELEASE_TAG }}

```

The stable version is still missing. The script shall create a stable image for the latest version tag? Maybe we need a second workflow here.

**Comment by GioF71** [comment]
Hello, a few questions for you. I hope you can help :-)

1) do I need to create "Environment secrets" or "Repository secrets"?

2) About the build process I made some changes lately, and got rid of all the release branches.
I built the latest version using the scripts:

build-bullseye-sourceforge.sh
build-bullseye.sh 
build-buster-sourceforge.sh
build-buster.sh
build-latest.sh
build-stable.sh

I had to change the build process for the sourceforge version because it occurred to me that sourceforge download just stopped working. I don't if it was due to some throttling, but I could not build anymore.
Currently for the "sourceforge" version, the Dockerfile expects the binaries to be in the correct places, which is not optimal.
I plan to build an intermediate image with all the binaries, unless I discover a way to selectively COPY the correct binary during the build phase, avoiding to copy all the binaries.

3) I would gladly support more platforms like you are suggesting. Can you suggest how to match the architectures with the sourceforge binaries? Here is the download page.
https://sourceforge.net/projects/lmsclients/files/squeezelite/linux/
I can match x86_64 with amd64, armhf with armv7l and maybe arm64 with aarch64 (hopefully correctly), but does "armel" correspond to linux/arm/v6?

Thank you!

**Comment by Der-Henning** [comment]
Hi!
1. Repository Secrets. Now found under Settings -> Secrets -> Actions
2. Yes. The branches should only be used for different developement paths and not different versions.
The Downloads from Sourceforge should work. Maybe double check the download links? Again?
After installation you should delete the binary anyway, so you can copy them all and delete them all afterwards. Same for your `install.sh`.
3. To map the different arch names you can use an associative array [https://lzone.de/cheat-sheet/Bash%20Associative%20Array](https://lzone.de/cheat-sheet/Bash%20Associative%20Array)
````
declare -A arch_arr
arch_arr["linux/amd64"]="x86_64"
... etc.

echo ${arch_arr[${arch}]}
````
Then you have to define another matrix for the workflow with the different archs `arch: ['linux/amd64', 'linux/arm/v7', 'linux/arm64/v8']` and pass the arch as argument to your Dockerfile and set `platforms: ${{ matrix.arch }}` in the last step of the workflow. In your Dockerfile you can then pass the arch-argument to your install.sh and map it, as shown above, to the sourceforge-arch and download the corresponding release. 

If I have some time this weekend I will try to update this PR accordingly.

**Comment by GioF71** [comment]
About the multi-stage docker file... I was thinking of doing all the install in one instruction in the script, so that the image size would not become bigger than needed.
OTOH, I would like to minimize the downloads and avoid incurring in the same error with sourceforge (throttling or some error on their side, triggered by too many downloads in a certain amount of time).
I will need to experiment a little more.

**Comment by GioF71** [comment]
Hello, I have simplified the build process. It's not multistage anymore, and no assets are required, we are back to downloads.
Hope this simplifies your work!

**Comment by Der-Henning** [comment]
The new workflow creates the following tags:
[https://hub.docker.com/r/derhenning/squeezelite/tags](https://hub.docker.com/r/derhenning/squeezelite/tags)
"latest" is the same image as "bullseye-20220125-slim".
Does the result match your concept?

Had to add ` --no-check-certificate` to download from sourceforge on the focal arm image. Updating ca-certificates didn't work ...

**Comment by GioF71** [comment]
Hello, thank you! Yes, "latest" should match debian-bullseye with sourceforge download.
From what I see in the yaml file, it's done ok.
The only thing I believe is missing is the "stable" version, which should be "debian-buster" with no sourceforge download, can you add this one also?
Amazing work, thank you for taking the time working on this!

**Comment by GioF71** [comment]
Another thing, the dates I append to my images are related to the "release date" of the image, not of the base image.
Thanks!

**Comment by Der-Henning** [comment]
Update:

- Workflow not creates a tag only with [bullseye, buster, focal] and anotherone with the current date.
- Added stable tag to buster image.
- Excluded focal / sourceforge combination from workflow. -> removed `--no-check-certificate`

See created images on [hub.docker.com](https://hub.docker.com/r/derhenning/squeezelite/tags)

**Pull request merged**
